# Site settings
baseurl = "https://ozunconf18.ropensci.org"
canonifyurls = true
relativeurls = false
languageCode = "en-us"
title = "rOpenSci OzUnconference"
location = "Melbourne 2018"
theme = "hugo-ropensci-theme"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "rOpenSci OzUnconference"
  description = "Melbourne, Australia. 22-23 Novembe 2018"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Sorry, but you seem to have become lost."
    text = "Please visit [the front page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "rOpenSci"
    # Optional logo as brand stored in img/
    logo = "ropensci_small.png"
    about = "What"
    team = "Who"
    joinus="Join Us"
    venue = "Venue"
    sponsors = "Sponsors"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "rOpenSci OzUnconf"
    subtitle = "22-23 November 2018 • Melbourne • Australia"
    buttonText = "Tell me more"


   # About section
   [params.about]
    enable = true
    title = "The OzUnconference"
    text = "For a third year running, we are excited to announce another [rOpenSci](http://ropensci.org/) OzUnconference in 2018 held in Melbourne, Australia. We're organizing this event to bring together scientists, developers, and open data enthusiasts from academia, industry, government, and non-profit to get together for a few days and hack on various projects. [Past projects](http://ozunconf18.ropensci.org/projects/) have related to open data, data visualization, data publication and open science using R. To ensure a safe, enjoyable, and friendly experience for everyone who participates, we have a strict [code of conduct](/coc) and [terms and conditions](/terms).\n\n All OzUnconference ideas will begin as GitHub issues on the [OzUnconf repo](https://github.com/ropensci/ozunconf18/issues/) in the weeks before the event. However, the actual schedule will not be decided until the morning of the 22nd. You can see some of the [projects proposed](https://github.com/ropensci/ozunconf17/issues/) for last year's event in Australia, and the [projects proposed](https://github.com/ropensci/unconf18/issues) at the unconf in Seattle earlier this year."

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Participants"
    text = "We are assembling an exciting team of developers and enthusiastic users representing academia, industry, government, and various open source projects."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    
    [[params.team.members]]
      name = "Nicholas Tierney"
      position = "Monash University"
      img = "nicholas-tierney.jpg"
      twitter = "nj_tierney"
      github = "njtierney"
      url = "http://www.njtierney.com/"

    [[params.team.members]]
      name = "Di Cook"
      position = "Monash University"
      img = "di-cook.jpg"
      twitter = "visnut"
      github = "dicook"
      url = "http://dicook.org"

    [[params.team.members]]
      name = "Rob Hyndman"
      position = "Monash University"
      img = "rob-hyndman.png"
      twitter = "robjhyndman"
      github = "robjhyndman"
      url = "https://robjhyndman.com"


    [[params.team.members]]
      name = "Saskia Freytag"
      position = "Walter and Eliza Hall Institute"
      img = "saskia-freytag.jpg"
      twitter = "trashystats"
      github = ""
      url = "https://soundcloud.com/crediblycurious"
      
    [[params.team.members]]
      name = "Holly Kirk"
      position = "RMIT University"
      img = "holly-kirk.jpg"
      twitter = "HollyKirk"
      github = "hollylkirk"
      url = "https://natureonthebrain.wordpress.com/"

    [[params.team.members]]
      name = "Mathew Ling"
      position = "Deakin University"
      img = "mathew-ling.jpg"
      twitter = "lingtax"
      github = "Lingtax"
      url = "http://mathewling.com"


    [[params.team.members]]
      name = "Nick Golding"
      position = "University of Melbourne"
      img = "nick-golding.jpg"
      twitter = "_NickGolding_"
      github = "goldingn"
      url = "https://greta-dev.github.io/greta/"

    [[params.team.members]]
      name = "Emi Tanaka"
      position = "University of Sydney"
      img = "emi-tanaka.jpg"
      twitter = "statsgen"
      github = "emitanaka"
      url = "https://emitanaka.github.io/"

    [[params.team.members]]
      name = "Danielle Navarro"
      position = "University of New South Wales"
      img = "dani-navarro.jpg"
      twitter = "djnavarro"
      github = "djnavarro"
      url = "http://compcogscisydney.org/"

    [[params.team.members]]
      name = "Thomas Lumley"
      position = "University of Auckland"
      img = "thomas-lumley.jpg"
      twitter = "tslumley"
      github = "tslumley"
      url = "https://notstatschat.rbind.io/"
    
    [[params.team.members]]
      name = "Saras Windecker"
      position = "University of Melbourne"
      img = "saras-windecker.png"
      twitter = "smwindecker"
      github = "smwindecker"
      url = "https://www.smwindecker.com"

    [[params.team.members]]
      name = "Stefan Milton Bache"
      position = "Redbubble"
      img = "stefan-milton-bache.jpg"
      twitter = "stefanbache"
      github = "smbache"
      url = "http://stefanbache.dk/"
     

    [[params.team.members]]
      name = "Stuart Lee"
      position = "Monash / WEHI"
      img = "stuart-lee.jpg"
      twitter = "_StuartLee"
      github = "sa-lee"
      url = "http://stuartlee.org/"

    [[params.team.members]]
      name = "Felix Singleton Thorn"
      position = "University of Melbourne"
      img = "felix-st.png"
      twitter = "FSingletonThorn"
      github = "fsingletonthorn"
      url = "https://imerg.info"

    [[params.team.members]]
      name = "Emily Kothe"
      position = "Deakin University"
      img = "emily-kothe.jpg"
      twitter = "emilyandthelime"
      github = "ekothe"
      url = "https://emilykothe.com"

    [[params.team.members]]
      name = "Mitchell O'Hara-Wild"
      position = "Monash University"
      img = "mitch-ohara-wild.jpg"
      twitter = "mitchoharawild"
      github = "mitchelloharawild"
      url = "https://mitchelloharawild.com/"

    [[params.team.members]]
      name = "Alan Pearse"
      position = "Queensland University of Technology"
      img = "alan-pearse.jpg"
      twitter = "apear91"
      github = "github.com/apear9"
      url = "https://goo.gl/CNrbYB"

    [[params.team.members]]
      name = "Matt Johnson"
      position = "EPA Victoria"
      img = "matt-johnson.jpg"
      twitter = "mrjoh3"
      github = "mrjoh3"
      url = "https://mrjoh3.github.io"

    [[params.team.members]]
      name = "Mark Greenaway"
      position = "University of Sydney"
      img = "mark-greenaway.jpg"
      twitter = "certifiedwaif"
      github = "certifiedwaif"
      url = "NA"

    [[params.team.members]]
      name = "Sarah Romanes"
      position = "University of Sydney"
      img = "sarah-romanes.jpg"
      twitter = "sarah_romanes"
      github = "sarahromanes"
      url = "NA"

    [[params.team.members]]
      name = "Adam Gruer"
      position = "The Royal Children's Hospital Melbourne"
      img = "adam-gruer.jpg"
      twitter = "AdamGruer"
      github = "adam-gruer"
      url = "https://adamgruer.rbind.io/"

    [[params.team.members]]
      name = "Radoslaw Panczak"
      position = "University of Queensland"
      img = "radoslaw-panczak.png"
      twitter = "RPanczak"
      github = "RPanczak"
      url = "https://scholar.google.com/citations?user=8j-L0asAAAAJ&hl=en"

    [[params.team.members]]
      name = "Dan Wilson"
      position = "The Data Collective"
      img = "dan-wilson.jpeg"
      twitter = "danwwilson"
      github = "danwwilson"
      url = "https://www.google.com/url?q=https://thedatacollective.com.au&source=gmail&ust=1541652173896000&usg=AFQjCNE2XZl80yo19qHRCG4obJfO7rW_bQ"

    [[params.team.members]]
      name = "Amy Stringer"
      position = "Queensland University of Technology"
      img = "amy-stringer.jpeg"
      twitter = "AmyStringer11"
      github = "AmyStringer"
      url = "NA"

    [[params.team.members]]
      name = "Sadia Nawaz"
      position = "University of Melbourne"
      img = "sadia-nawaz.jpg"
      twitter = "1sadiaz"
      github = "sadian"
      url = "https://www.researchgate.net/profile/Sadia_Nawaz3"

    [[params.team.members]]
      name = "Anna Quaglieri"
      position = "WEHI"
      img = "anna-quaglieri.jpg"
      twitter = "annaquagli"
      github = "annaquaglieri16"
      url = "NA"

    [[params.team.members]]
      name = "Rhydwyn Mcguire"
      position = "Health Protection NSW"
      img = "rhydwyn-mcguire.jpg"
      twitter = "Rhydwyn"
      github = "NA"
      url = "Rhydwyn"

    [[params.team.members]]
      name = "Nathan Lane"
      position = "Monash University"
      img = "nathan-lane.jpg"
      twitter = "straightedge"
      github = "nathanlane"
      url = "http://nathanlane.info/"

    [[params.team.members]]
      name = "Gabriela D'Souza"
      position = "[CEDA](https://ceda.com.au/)"
      img = "gabriella-dsouza.JPG"
      twitter = "gabster0191"
      github = "gabyd"
      url = "https://gdsouza0191.wixsite.com/mysite"

    [[params.team.members]]
      name = "Ben Raymond"
      position = "Australian Antarctic Division & University of Tasmania"
      img = "ben-raymond.jpg"
      twitter = "NA"
      github = "raymondben"
      url = "https://github.com/raymondben/"

    [[params.team.members]]
      name = "Jennifer Beaudry"
      position = "Swinburne University of Technology"
      img = "jennifer-beaudry.jpg"
      twitter = "drjbeaudry"
      github = "NA"
      url = "http://www.swinburne.edu.au/health-arts-design/staff/profile/index.php?id=jbeaudry"

    [[params.team.members]]
      name = "Roni Hang"
      position = "Transport for NSW"
      img = "roni-hang.jpg"
      twitter = "dataroni8"
      github = "dataroni8"
      url = "https://www.linkedin.com/in/roni-hang-144543161/"

    [[params.team.members]]
      name = "Elise Gould"
      position = "University of Melbourne"
      img = "elise-gould.jpg"
      twitter = "EliseGould"
      github = "egouldo"
      url = "https://egouldo.github.io/"

    [[params.team.members]]
      name = "Jackson Kwok"
      position = "University of Melbourne"
      img = "jackson-kwok.png"
      twitter = "NA"
      github = "https://github.com/kcf-jackson"
      url = "https://www.google.com/url?q=https://github.com/kcf-jackson/&source=gmail&ust=1541652995376000&usg=AFQjCNHVSMygOZ1T3z5YSXmzZJIezJdnJQ"

    [[params.team.members]]
      name = "Felix Leung"
      position = "BOCSAR"
      img = "felix-leung.jpg"
      twitter = "https://twitter.com/felixleungsc"
      github = "http://gitlab.com/felixleungsc"
      url = "https://gitlab.com/felixleungsc"

    [[params.team.members]]
      name = "Mike Cheng"
      position = "Model Answers"
      img = "mike-cheng.jpeg"
      twitter = "coolbutuseless"
      github = "coolbutuseless"
      url = "http://model-a.com.au/"

    [[params.team.members]]
      name = "Laura de Jong"
      position = "Deakin University"
      img = "laura-dejong.jpg"
      twitter = "LMSdeJong"
      github = "Not yet there"
      url = "https://twitter.com/LMSdeJong"

    [[params.team.members]]
      name = "Robbie Bonelli"
      position = "WEHI"
      img = "robbie-bonelli.jpg"
      twitter = "robbie_bonelli"
      github = "Robbie90"
      url = "https://www.linkedin.com/in/roberto-bonelli/"

    [[params.team.members]]
      name = "Claire Miller"
      position = "University of Melbourne"
      img = "claire-miller.png"
      twitter = "NA"
      github = "clairemiller"
      url = "NA"

    [[params.team.members]]
      name = "Steven Kambouris"
      position = "University of Melbourne"
      img = "steven-kambouris.jpg"
      twitter = "steve_kambouris"
      github = "stevekambouris"
      url = "https://imerg.info/"

    [[params.team.members]]
      name = "Jessie Roberts"
      position = "ACEMS, QUT"
      img = "jessie-roberts.jpg"
      twitter = "_jessie_roberts"
      github = "Jesse-jesse"
      url = "NA"

    [[params.team.members]]
      name = "Mark Dulhunty"
      position = "EMS"
      img = "mark-dulhunty.jpg"
      twitter = "markdly_"
      github = "markdly"
      url = "https://markdly.github.io/"

    [[params.team.members]]
      name = "Peggy Newman"
      position = "Atlas of Living Australia"
      img = "peg-newman.jpg"
      twitter = "peg_newman"
      github = "peggynewman"
      url = "http://ala.org.au"
      
# Join us section
  [params.joinus]
  enable=true
  title = "Join us (Nominations have now closed)"
  text = "The rOpenSci OzUnconference is our annual event loosely modeled on Foo Camp. This event is unlike many other unconferences in that it is mostly invite-only (past attendees often recommend new ones) with a few spots set aside for self-nominations from the community at large. The agenda is mostly decided during the conference itself. \n\n   Nominations are closed for the ozunconf 2018, but stay tuned for the 2019 ozunconf announcement mid 2019."

# Venue section
  [params.venue]
  enable=true
  title = "Venue"
  text = "The event will be hosted at the [University of Melbourne Arts West North Wing Rooms 453-455](https://maps.unimelb.edu.au/parkville/building/148a), Building 148a University of Melbourne"
  map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3152.7033155773374!2d144.95810256588925!3d-37.79699214085815!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad65cd487b6a0b9%3A0xde2eb4f06c537678!2sArts+West%2C+The+University+of+Melbourne!5e0!3m2!1sen!2sau!4v1536732339717"


  # Sponsors section

    [params.sponsors_list]
      enable = true
      # Possibility to center items
      #center = true
      title = "Sponsors"
      text = "We are extremely grateful to all the sponsors for this year's event. If your organization would like to sponsor the OzUnconf, please email nicholas.tierney [at] monash edu for a sponsorship prospectus."

      # All the clients' logos are stored under 'static/img/sponsors'.
      # Replace them with your sponsors's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.sponsors]]
        logo = "ropensci-lettering-colour.png"
        link = "https://ropensci.org"
        
      [[params.sponsors]]
        logo = "microsoft-azure.png"
        link = "https://www.r-consortium.org/"
      
      [[params.sponsors]]
        logo = "RConsortium.png"
        link = "https://www.r-consortium.org/"
      
      [[params.sponsors]]
        logo = "rstudio-logo.png"
        link = "https://rstudio.com"
      
      [[params.sponsors]]
        logo = "unimelb.png"
        link = "https://www.unimelb.edu.au/"
      
      [[params.sponsors]]
        logo = "monash-business-school.jpg"
        link = "https://www.monash.edu/business"


  # Contact section
  [params.contact]
    enable = false
    title = "Contact us"
    text  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "nicholas.tierney@monash.edu"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."
    text = "[Contact us](https://njtierney.typeform.com/to/WrmNJO) for more information about the event. This page is available at [this repo](https://github.com/ropensci/ozunconf18). Corrections, changes, and suggestions for improvement are welcome as pull requests."

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
